export const universities = [
  {
    id: "graphic-era",
    name: "Graphic Era University",
    shortName: "GE",
    country: "India",
    city: "Dehradun",
    established: 1993,
    ranking: 42,
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&q=80",
    logo: "GE",
    logoColor: "#1a56db",
    description: "Graphic Era University is a premier institution known for its excellence in technology, engineering, and management education. Located in the scenic foothills of the Himalayas in Dehradun, it offers world-class infrastructure and internationally recognized programs.",
    programs: {
      undergraduate: ["Computer Science", "Information Technology", "Business Administration", "Nursing", "Engineering", "Agriculture", "Commerce", "Law"],
      postgraduate: ["MBA", "MSc Computer Science", "MA English", "PhD Programs", "MTech", "MCA"]
    },
    tuition: { min: 2500, max: 6000, currency: "USD" },
    scholarship: true,
    scholarships: ["Merit Scholarship (up to 50%)", "Sports Scholarship", "International Student Scholarship"],
    rating: 4.7,
    students: 12000,
    facultyRatio: "1:15",
    website: "https://geu.ac.in",
    accreditation: "NAAC A+",
    tags: ["Technology", "Engineering", "Management"],
    highlights: ["NBA Accredited", "International Exchange Programs", "100+ Research Centers", "Smart Campus"],
    video: "https://www.youtube.com/embed/XuW9Yc6Ow2E",
    gallery: [
      "https://images.unsplash.com/photo-1562774053-701939374585?w=600&q=80",
      "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&q=80",
      "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&q=80",
      "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=600&q=80",
    ],
    accommodation: { available: true, cost: "800-1500 USD/year", types: ["Single Room", "Double Room", "Suite"] },
    placement: "92%",
  },
  {
    id: "pp-savani",
    name: "PP Savani University",
    shortName: "PPSU",
    country: "India",
    city: "Surat",
    established: 2018,
    ranking: 78,
    image: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&q=80",
    logo: "PPSU",
    logoColor: "#0e9f6e",
    description: "PP Savani University, located in Surat, Gujarat, is a modern university offering cutting-edge programs in engineering, management, sciences, and healthcare. The university is known for its industry connections and research-driven curriculum.",
    programs: {
      undergraduate: ["Computer Science", "Mechanical Engineering", "Civil Engineering", "Pharmacy", "Business Administration", "Nursing"],
      postgraduate: ["MBA", "MTech", "MSc", "PhD Programs", "MCA"]
    },
    tuition: { min: 2000, max: 5500, currency: "USD" },
    scholarship: true,
    scholarships: ["Academic Excellence Scholarship", "Need-Based Aid", "Sports Excellence Award"],
    rating: 4.5,
    students: 8500,
    facultyRatio: "1:18",
    website: "https://ppsavani.edu.in",
    accreditation: "NAAC A",
    tags: ["Engineering", "Healthcare", "Business"],
    highlights: ["Industry 4.0 Labs", "Innovation Hub", "International Collaborations", "Green Campus"],
    video: "https://www.youtube.com/embed/bsV4_nIV2sU",
    gallery: [
      "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=600&q=80",
      "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=600&q=80",
      "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?w=600&q=80",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=80",
    ],
    accommodation: { available: true, cost: "700-1200 USD/year", types: ["Single Room", "Double Room"] },
    placement: "88%",
  },
  {
    id: "gulzar-group",
    name: "Gulzar Group of Institutes",
    shortName: "GGI",
    country: "India",
    city: "Ludhiana",
    established: 2001,
    ranking: 95,
    image: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800&q=80",
    logo: "GGI",
    logoColor: "#7e3af2",
    description: "Gulzar Group of Institutes is one of Punjab's leading educational institutions offering diverse programs across engineering, management, pharmacy, and arts. With state-of-the-art facilities and experienced faculty, GGI provides excellent career opportunities.",
    programs: {
      undergraduate: ["Computer Science", "Electronics", "Pharmacy", "Business Administration", "Agriculture", "Fashion Design"],
      postgraduate: ["MBA", "MTech", "MSc Pharmacy", "PhD Programs"]
    },
    tuition: { min: 1800, max: 4500, currency: "USD" },
    scholarship: true,
    scholarships: ["Merit Scholarship", "Rural Student Scholarship", "Girls Scholarship"],
    rating: 4.3,
    students: 10000,
    facultyRatio: "1:20",
    website: "https://ggi.ac.in",
    accreditation: "NAAC B++",
    tags: ["Pharmacy", "Engineering", "Agriculture"],
    highlights: ["Pharmacy Research Labs", "Agricultural Fields", "Sports Complex", "Cultural Hub"],
    video: "https://www.youtube.com/embed/eCr_U6N5dHA",
    gallery: [
      "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=600&q=80",
      "https://images.unsplash.com/photo-1613904133939-f3d5ef6c7e71?w=600&q=80",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80",
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=600&q=80",
    ],
    accommodation: { available: true, cost: "600-1000 USD/year", types: ["Shared Room", "Double Room"] },
    placement: "85%",
  },
  {
    id: "mats-university",
    name: "MATS University",
    shortName: "MATS",
    country: "India",
    city: "Raipur",
    established: 2006,
    ranking: 112,
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
    logo: "MATS",
    logoColor: "#e3a008",
    description: "MATS University in Raipur, Chhattisgarh offers quality education in engineering, management, law, and education. Known for its affordable tuition and strong alumni network, MATS provides excellent value for international students.",
    programs: {
      undergraduate: ["Computer Science", "Civil Engineering", "Law", "Education", "Commerce", "Hotel Management"],
      postgraduate: ["MBA", "LLM", "MEd", "MTech", "PhD Programs"]
    },
    tuition: { min: 1500, max: 4000, currency: "USD" },
    scholarship: true,
    scholarships: ["Academic Merit Award", "International Student Grant", "Financial Need Scholarship"],
    rating: 4.2,
    students: 7500,
    facultyRatio: "1:22",
    website: "https://matsuniversity.ac.in",
    accreditation: "NAAC B+",
    tags: ["Law", "Education", "Hotel Management"],
    highlights: ["Moot Court", "Hotel Management Kitchen", "Digital Library", "Eco-Friendly Campus"],
    video: "https://www.youtube.com/embed/toDqZc-Hcs0",
    gallery: [
      "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&q=80",
      "https://images.unsplash.com/photo-1599687351724-dfa3c4ff81b1?w=600&q=80",
      "https://images.unsplash.com/photo-1606761568499-6d2451b23c66?w=600&q=80",
      "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=600&q=80",
    ],
    accommodation: { available: true, cost: "500-900 USD/year", types: ["Shared Room", "Double Room", "Single Room"] },
    placement: "82%",
  },
  {
    id: "sr-university",
    name: "SR University",
    shortName: "SRU",
    country: "India",
    city: "Warangal",
    established: 2013,
    ranking: 87,
    image: "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?w=800&q=80",
    logo: "SRU",
    logoColor: "#f05252",
    description: "SR University in Warangal, Telangana is a dynamic institution focused on engineering, technology, and management education. With a research-oriented approach and modern labs, SRU prepares students for global careers in the tech industry.",
    programs: {
      undergraduate: ["Computer Science", "AI & ML", "Data Science", "Electrical Engineering", "Mechanical Engineering", "Business Administration"],
      postgraduate: ["MTech AI", "MBA Technology", "MSc Data Science", "PhD Engineering"]
    },
    tuition: { min: 2200, max: 5000, currency: "USD" },
    scholarship: true,
    scholarships: ["Tech Excellence Award", "Innovation Scholarship", "Merit-Based Financial Aid"],
    rating: 4.6,
    students: 6000,
    facultyRatio: "1:16",
    website: "https://sru.edu.in",
    accreditation: "NAAC A",
    tags: ["AI/ML", "Data Science", "Technology"],
    highlights: ["AI Research Center", "Industry 4.0 Labs", "Startup Incubator", "International Faculty"],
    video: "https://www.youtube.com/embed/3Ir4C6wdn3o",
    gallery: [
      "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?w=600&q=80",
      "https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=600&q=80",
      "https://images.unsplash.com/photo-1525921429624-479b6a26d84d?w=600&q=80",
      "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=600&q=80",
    ],
    accommodation: { available: true, cost: "700-1300 USD/year", types: ["Single Room", "Double Room"] },
    placement: "94%",
  },
  {
    id: "marwadi-university",
    name: "Marwadi University",
    shortName: "MU",
    country: "India",
    city: "Rajkot",
    established: 2016,
    ranking: 65,
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&q=80",
    logo: "MU",
    logoColor: "#0694a2",
    description: "Marwadi University in Rajkot, Gujarat is a UGC-recognized university known for innovation, entrepreneurship, and holistic education. With a thriving startup ecosystem and strong industry partnerships, MU offers excellent career prospects.",
    programs: {
      undergraduate: ["Computer Engineering", "Information Technology", "Chemical Engineering", "Business Administration", "Applied Sciences", "Design"],
      postgraduate: ["MBA", "MTech", "MSc", "PhD Programs", "PG Diploma"]
    },
    tuition: { min: 2500, max: 5500, currency: "USD" },
    scholarship: true,
    scholarships: ["Startup Scholarship", "Excellence Award", "Sports Scholarship", "International Grant"],
    rating: 4.8,
    students: 9000,
    facultyRatio: "1:14",
    website: "https://marwadiuniversity.ac.in",
    accreditation: "NAAC A+",
    tags: ["Innovation", "Entrepreneurship", "Engineering"],
    highlights: ["Top NAAC A+ Rating", "Startup Incubator with 50+ Startups", "International Exchange", "Industry 4.0 Lab"],
    video: "https://www.youtube.com/embed/Ni3ScjGpVjI",
    gallery: [
      "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&q=80",
      "https://images.unsplash.com/photo-1551636898-47668aa61de2?w=600&q=80",
      "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&q=80",
      "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=600&q=80",
    ],
    accommodation: { available: true, cost: "800-1400 USD/year", types: ["Single Room", "Double Room", "Suite"] },
    placement: "96%",
  },
  {
    id: "desh-bhagat",
    name: "Desh Bhagat University",
    shortName: "DBU",
    country: "India",
    city: "Mandi Gobindgarh",
    established: 2012,
    ranking: 103,
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&q=80",
    logo: "DBU",
    logoColor: "#3f83f8",
    description: "Desh Bhagat University is a premier private university in Punjab offering comprehensive programs in engineering, sciences, agriculture, management and arts. Known for value-based education and excellent placement records.",
    programs: {
      undergraduate: ["Computer Science", "Agriculture", "Nursing", "Pharmacy", "Physical Education", "Fashion Design"],
      postgraduate: ["MBA", "MSc Agriculture", "MPharm", "PhD Programs", "MEd"]
    },
    tuition: { min: 1800, max: 4200, currency: "USD" },
    scholarship: true,
    scholarships: ["Merit Scholarship", "Agriculture Excellence Award", "Sports Scholarship"],
    rating: 4.4,
    students: 11000,
    facultyRatio: "1:19",
    website: "https://deshbhagatuniversity.in",
    accreditation: "NAAC A",
    tags: ["Agriculture", "Nursing", "Education"],
    highlights: ["Agricultural Research Farm", "Nursing Skills Lab", "State Sports Facilities", "Cultural Heritage Center"],
    video: "https://www.youtube.com/embed/DQIeqtHsdi4",
    gallery: [
      "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&q=80",
      "https://images.unsplash.com/photo-1593642532454-e138e28a63f4?w=600&q=80",
      "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=600&q=80",
      "https://images.unsplash.com/photo-1565017228285-8b9f45f6a7db?w=600&q=80",
    ],
    accommodation: { available: true, cost: "600-1100 USD/year", types: ["Shared Room", "Double Room"] },
    placement: "87%",
  },
  {
    id: "lpu",
    name: "Lovely Professional University",
    shortName: "LPU",
    country: "India",
    city: "Phagwara",
    established: 2005,
    ranking: 28,
    image: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&q=80",
    logo: "LPU",
    logoColor: "#ff5a1f",
    description: "Lovely Professional University is one of India's largest private universities, renowned globally for its diverse programs, world-class infrastructure, and exceptional placement record. With 30,000+ students from 50+ countries, LPU is a truly global university.",
    programs: {
      undergraduate: ["Computer Science", "IT", "Business Administration", "Design", "Law", "Agriculture", "Hotel Management", "Film Studies"],
      postgraduate: ["MBA", "MTech", "MSc", "LLM", "PhD Programs", "MCA", "MArch"]
    },
    tuition: { min: 3000, max: 7000, currency: "USD" },
    scholarship: true,
    scholarships: ["Chancellor's Excellence Scholarship", "Academic Merit Award", "Sports Championship Scholarship", "International Student Grant"],
    rating: 4.9,
    students: 30000,
    facultyRatio: "1:12",
    website: "https://lpu.in",
    accreditation: "NAAC A++",
    tags: ["Global University", "Industry Connect", "Research"],
    highlights: ["QS World Ranked", "30,000+ Students", "50+ Countries", "600+ Programs", "World-Class Campus"],
    video: "https://www.youtube.com/embed/coEaOaAhxTs",
    gallery: [
      "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=600&q=80",
      "https://images.unsplash.com/photo-1562774053-701939374585?w=600&q=80",
      "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=600&q=80",
      "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=600&q=80",
    ],
    accommodation: { available: true, cost: "900-1800 USD/year", types: ["Single Room", "Double Room", "Suite", "Apartment"] },
    placement: "98%",
  },
  {
    id: "royal-global",
    name: "Royal Global University",
    shortName: "RGU",
    country: "India",
    city: "Guwahati",
    established: 2013,
    ranking: 118,
    image: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=800&q=80",
    logo: "RGU",
    logoColor: "#c81e1e",
    description: "Royal Global University in Guwahati, Assam offers quality education in management, engineering, healthcare, and social sciences. Strategically located in Northeast India, RGU provides unique opportunities for students interested in the region's growing economy.",
    programs: {
      undergraduate: ["Business Administration", "Computer Applications", "Nursing", "Social Work", "Hospitality Management"],
      postgraduate: ["MBA", "MCA", "MSc Nursing", "MSW", "PhD Programs"]
    },
    tuition: { min: 1600, max: 4000, currency: "USD" },
    scholarship: true,
    scholarships: ["Regional Merit Award", "Healthcare Excellence Scholarship", "First Generation Learner Grant"],
    rating: 4.1,
    students: 5000,
    facultyRatio: "1:20",
    website: "https://rgu.ac",
    accreditation: "NAAC B++",
    tags: ["Healthcare", "Management", "Social Work"],
    highlights: ["Northeast India's Hub", "Healthcare Training Center", "Social Entrepreneurship Lab"],
    video: "https://www.youtube.com/embed/pZnaKowtN8w",
    gallery: [
      "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=600&q=80",
      "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?w=600&q=80",
      "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=600&q=80",
      "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=600&q=80",
    ],
    accommodation: { available: true, cost: "500-950 USD/year", types: ["Shared Room", "Double Room"] },
    placement: "80%",
  },
  {
    id: "sharda",
    name: "SHARDA University",
    shortName: "SU",
    country: "India",
    city: "Greater Noida",
    established: 2009,
    ranking: 52,
    image: "https://images.unsplash.com/photo-1550305080-4e029753abcf?w=800&q=80",
    logo: "SU",
    logoColor: "#8e4b10",
    description: "Sharda University, located in Greater Noida near Delhi, is one of the fastest-growing private universities in India. Known for its international student community, diverse programs, and excellent research facilities.",
    programs: {
      undergraduate: ["Computer Science", "Engineering", "Law", "Medicine", "Dentistry", "Architecture", "Business"],
      postgraduate: ["MBA", "MTech", "LLM", "MD", "PhD Programs", "MSc"]
    },
    tuition: { min: 3500, max: 8000, currency: "USD" },
    scholarship: true,
    scholarships: ["International Excellence Scholarship", "Academic Merit Award", "STEM Scholarship"],
    rating: 4.6,
    students: 18000,
    facultyRatio: "1:13",
    website: "https://sharda.ac.in",
    accreditation: "NAAC A+",
    tags: ["Medical", "Law", "International"],
    highlights: ["Medical & Dental Colleges", "150+ International MOU", "Delhi NCR Location", "World-Class Research"],
    video: "https://www.youtube.com/embed/Kw4Af3hN8fk",
    gallery: [
      "https://images.unsplash.com/photo-1550305080-4e029753abcf?w=600&q=80",
      "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=600&q=80",
      "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&q=80",
      "https://images.unsplash.com/photo-1506818144585-74b29c980d4b?w=600&q=80",
    ],
    accommodation: { available: true, cost: "1000-2000 USD/year", types: ["Single Room", "Double Room", "Suite"] },
    placement: "95%",
  },
  {
    id: "amity",
    name: "Amity University",
    shortName: "AU",
    country: "India",
    city: "Noida",
    established: 2005,
    ranking: 22,
    image: "https://images.unsplash.com/photo-1554188248-986adbb73be4?w=800&q=80",
    logo: "AU",
    logoColor: "#0f172a",
    description: "Amity University is India's most renowned private university with global campuses. Known for its world-class research, strong industry connections, and diverse academic programs, Amity consistently ranks among India's top universities.",
    programs: {
      undergraduate: ["Computer Science", "Engineering", "Business", "Law", "Media Studies", "Design", "Biotechnology"],
      postgraduate: ["MBA", "MTech", "LLM", "MSc Biotechnology", "PhD Programs", "MA Design"]
    },
    tuition: { min: 4000, max: 9000, currency: "USD" },
    scholarship: true,
    scholarships: ["Chancellor's Scholarship", "Research Excellence Award", "Global Merit Scholarship", "Sports Achievement Award"],
    rating: 4.8,
    students: 25000,
    facultyRatio: "1:11",
    website: "https://amity.edu",
    accreditation: "NAAC A++",
    tags: ["Top Ranked", "Research", "Global"],
    highlights: ["QS World Top 300", "Global Campuses", "200+ MoUs Worldwide", "Industry-Ready Programs"],
    video: "https://www.youtube.com/embed/RWH1MpQ_Zng",
    gallery: [
      "https://images.unsplash.com/photo-1554188248-986adbb73be4?w=600&q=80",
      "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&q=80",
      "https://images.unsplash.com/photo-1562774053-701939374585?w=600&q=80",
      "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&q=80",
    ],
    accommodation: { available: true, cost: "1200-2500 USD/year", types: ["Single Room", "Double Room", "Suite", "Apartment"] },
    placement: "97%",
  },
  {
    id: "khalsa",
    name: "Khalsa University",
    shortName: "KU",
    country: "India",
    city: "Amritsar",
    established: 2015,
    ranking: 125,
    image: "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=800&q=80",
    logo: "KU",
    logoColor: "#1c64f2",
    description: "Khalsa University in Amritsar, Punjab is a culturally rich institution offering programs in engineering, sciences, humanities, and commerce. Located near the Golden Temple, it offers students a unique cultural experience alongside quality education.",
    programs: {
      undergraduate: ["Computer Science", "Commerce", "Arts", "Science", "Physical Education", "Punjabi Studies"],
      postgraduate: ["MBA", "MSc", "MA", "PhD Programs", "MEd"]
    },
    tuition: { min: 1400, max: 3500, currency: "USD" },
    scholarship: true,
    scholarships: ["Sikh Heritage Scholarship", "Academic Excellence Award", "Sports Scholarship"],
    rating: 4.2,
    students: 6500,
    facultyRatio: "1:21",
    website: "https://khalsauniversity.org",
    accreditation: "NAAC B+",
    tags: ["Heritage", "Arts", "Sciences"],
    highlights: ["Cultural Heritage Center", "Punjabi Language Research", "Golden Temple Proximity", "Sports Academy"],
    video: "https://www.youtube.com/embed/paVk-PPl2r0",
    gallery: [
      "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=600&q=80",
      "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=600&q=80",
      "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=600&q=80",
      "https://images.unsplash.com/photo-1497366858526-0766d9dae979?w=600&q=80",
    ],
    accommodation: { available: true, cost: "450-800 USD/year", types: ["Shared Room", "Double Room"] },
    placement: "78%",
  },
  {
    id: "invertis",
    name: "Invertis University",
    shortName: "IU",
    country: "India",
    city: "Bareilly",
    established: 2010,
    ranking: 138,
    image: "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800&q=80",
    logo: "IU",
    logoColor: "#057a55",
    description: "Invertis University in Bareilly, Uttar Pradesh offers quality professional education in management, technology, law, and sciences. Known for its industry-oriented curriculum and practical learning approach.",
    programs: {
      undergraduate: ["Computer Science", "Business Administration", "Law", "Journalism", "Fine Arts", "Pharmacy"],
      postgraduate: ["MBA", "MTech", "LLM", "MCA", "PhD Programs"]
    },
    tuition: { min: 1300, max: 3800, currency: "USD" },
    scholarship: true,
    scholarships: ["Merit Scholarship", "Rural Achievers Award", "Girl Student Scholarship"],
    rating: 4.0,
    students: 5500,
    facultyRatio: "1:22",
    website: "https://invertis.org",
    accreditation: "NAAC B",
    tags: ["Law", "Journalism", "Technology"],
    highlights: ["Media Production Studio", "Legal Aid Clinic", "Pharmaceutical Lab", "Career Placement Cell"],
    video: "https://www.youtube.com/embed/fE5Uit93NvI",
    gallery: [
      "https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=600&q=80",
      "https://images.unsplash.com/photo-1497366858526-0766d9dae979?w=600&q=80",
      "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&q=80",
      "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=600&q=80",
    ],
    accommodation: { available: true, cost: "400-750 USD/year", types: ["Shared Room", "Double Room"] },
    placement: "75%",
  },
  {
    id: "mvm-institute",
    name: "MVM Institute",
    shortName: "MVM",
    country: "India",
    city: "Bhopal",
    established: 1999,
    ranking: 155,
    image: "https://images.unsplash.com/photo-1497366858526-0766d9dae979?w=800&q=80",
    logo: "MVM",
    logoColor: "#6875f5",
    description: "MVM Institute in Bhopal is a well-established educational institution offering programs in commerce, humanities, and applied sciences. With affordable tuition and quality education, MVM is ideal for students seeking value-for-money options.",
    programs: {
      undergraduate: ["Commerce", "Arts", "Science", "Computer Applications", "Home Science"],
      postgraduate: ["MCom", "MA", "MSc", "MCA", "PhD Programs"]
    },
    tuition: { min: 1000, max: 2800, currency: "USD" },
    scholarship: true,
    scholarships: ["Academic Merit Award", "Need-Based Scholarship", "Women Empowerment Scholarship"],
    rating: 3.9,
    students: 4000,
    facultyRatio: "1:24",
    website: "https://mvminstitute.ac.in",
    accreditation: "NAAC B",
    tags: ["Commerce", "Arts", "Sciences"],
    highlights: ["Affordable Education", "Strong Alumni Network", "Cultural Programs", "Women-Friendly Campus"],
    video: "https://www.youtube.com/embed/Sr1Tn-crCxU",
    gallery: [
      "https://images.unsplash.com/photo-1497366858526-0766d9dae979?w=600&q=80",
      "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&q=80",
      "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=600&q=80",
      "https://images.unsplash.com/photo-1562564055-71e051d33c19?w=600&q=80",
    ],
    accommodation: { available: true, cost: "350-650 USD/year", types: ["Shared Room", "Double Room"] },
    placement: "72%",
  },
  {
    id: "soa-university",
    name: "SOA University",
    shortName: "SOA",
    country: "India",
    city: "Bhubaneswar",
    established: 2007,
    ranking: 48,
    image: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800&q=80",
    logo: "SOA",
    logoColor: "#e74694",
    description: "Siksha 'O' Anusandhan (SOA) University in Bhubaneswar, Odisha is a NAAC A++ institution with strong research focus. Offering medical, dental, nursing, engineering, and management programs, SOA is recognized globally for its academic excellence.",
    programs: {
      undergraduate: ["Medicine", "Dentistry", "Nursing", "Engineering", "Pharmacy", "Business Administration"],
      postgraduate: ["MD", "MDS", "MSc Nursing", "MTech", "MBA", "PhD Programs"]
    },
    tuition: { min: 3000, max: 10000, currency: "USD" },
    scholarship: true,
    scholarships: ["Research Excellence Scholarship", "Medical Merit Award", "International Student Grant"],
    rating: 4.7,
    students: 20000,
    facultyRatio: "1:12",
    website: "https://soa.ac.in",
    accreditation: "NAAC A++",
    tags: ["Medical", "Research", "Engineering"],
    highlights: ["NAAC A++ Ranked", "1000-bed Teaching Hospital", "Research Publications Top 50", "International Collaborations"],
    video: "https://www.youtube.com/embed/0oLl_3YEtd4",
    gallery: [
      "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=600&q=80",
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80",
      "https://images.unsplash.com/photo-1551076805-e1869033e561?w=600&q=80",
      "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=600&q=80",
    ],
    accommodation: { available: true, cost: "900-1600 USD/year", types: ["Single Room", "Double Room", "Suite"] },
    placement: "94%",
  },
  {
    id: "cyrus-west",
    name: "Cyrus West University",
    shortName: "CWU",
    country: "North Cyprus",
    city: "Famagusta",
    established: 2010,
    ranking: 180,
    image: "https://images.unsplash.com/photo-1506818144585-74b29c980d4b?w=800&q=80",
    logo: "CWU",
    logoColor: "#7e3af2",
    description: "Cyrus West University in Famagusta, North Cyprus offers internationally recognized degrees in a Mediterranean setting. With English-medium instruction and a diverse student community, CWU is increasingly popular among African students seeking European-standard education.",
    programs: {
      undergraduate: ["Business Administration", "Computer Engineering", "International Relations", "Psychology", "Nursing", "Architecture"],
      postgraduate: ["MBA", "MSc Computer Engineering", "MA International Relations", "MSc Clinical Psychology", "PhD Programs"]
    },
    tuition: { min: 3500, max: 7500, currency: "USD" },
    scholarship: true,
    scholarships: ["International Merit Scholarship (up to 75%)", "African Student Scholarship", "Academic Excellence Award"],
    rating: 4.4,
    students: 8000,
    facultyRatio: "1:16",
    website: "https://cyruswest.edu.tr",
    accreditation: "YÖK Recognized, FIBAA Accredited",
    tags: ["Mediterranean", "International", "English-Medium"],
    highlights: ["European Standards", "Mediterranean Climate", "Affordable Cost of Living", "International Recognition"],
    video: "https://www.youtube.com/embed/c0auZbBHjpI",
    gallery: [
      "https://images.unsplash.com/photo-1506818144585-74b29c980d4b?w=600&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
      "https://images.unsplash.com/photo-1499678329028-101435549a4e?w=600&q=80",
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&q=80",
    ],
    accommodation: { available: true, cost: "1200-2200 USD/year", types: ["Single Room", "Double Room", "Studio Apartment"] },
    placement: "85%",
  },
  {
    id: "cyrus-international",
    name: "Cyrus International University",
    shortName: "CIU",
    country: "North Cyprus",
    city: "Nicosia",
    established: 2008,
    ranking: 165,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    logo: "CIU",
    logoColor: "#1a56db",
    description: "Cyrus International University in Nicosia, North Cyprus is a premier institution offering internationally accredited programs. With its stunning Mediterranean campus and world-class faculty, CIU provides students with a truly global educational experience.",
    programs: {
      undergraduate: ["Law", "Medicine", "Engineering", "Business", "Education", "Tourism Management"],
      postgraduate: ["LLM", "MBA", "MTech", "MSc", "MEd", "PhD Programs"]
    },
    tuition: { min: 4000, max: 9000, currency: "USD" },
    scholarship: true,
    scholarships: ["International Excellence Scholarship (up to 80%)", "African Development Scholarship", "Merit-Based Tuition Waiver"],
    rating: 4.6,
    students: 12000,
    facultyRatio: "1:14",
    website: "https://cyrusinternational.edu.tr",
    accreditation: "YÖK Recognized, AACSB Candidate",
    tags: ["Law", "Medicine", "International"],
    highlights: ["EU-Recognized Degrees", "Nicosia Capital City", "International Faculty", "Mediterranean Lifestyle"],
    video: "https://www.youtube.com/embed/OeP3EAnnzFA",
    gallery: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&q=80",
      "https://images.unsplash.com/photo-1499678329028-101435549a4e?w=600&q=80",
      "https://images.unsplash.com/photo-1506818144585-74b29c980d4b?w=600&q=80",
    ],
    accommodation: { available: true, cost: "1400-2500 USD/year", types: ["Single Room", "Double Room", "Suite", "Apartment"] },
    placement: "90%",
  },
];

export const testimonials = [
  {
    name: "Emmanuel Kollie",
    university: "Lovely Professional University, India",
    program: "BSc Computer Science",
    year: "2023",
    image: "https://images.unsplash.com/photo-1531384441138-2736e62e0919?w=150&q=80",
    story: "Tolbert Innovation Hub made my dream of studying abroad a reality. From document preparation to visa guidance, they were with me every step. Now I'm pursuing my passion in Computer Science at LPU!",
    rating: 5,
  },
  {
    name: "Patience Saah",
    university: "Amity University, India",
    program: "MBA International Business",
    year: "2023",
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&q=80",
    story: "I never thought studying at a top Indian university was possible from Liberia. The team at Tolbert Innovation Hub guided me through the entire process and helped me secure a 50% scholarship!",
    rating: 5,
  },
  {
    name: "James Brownell",
    university: "Cyrus International University, North Cyprus",
    program: "LLB Law",
    year: "2024",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    story: "North Cyprus was not on my radar until the counselors at Tolbert Innovation Hub showed me the opportunities. The EU-recognized degree and affordable tuition made it the perfect choice for my legal career.",
    rating: 5,
  },
  {
    name: "Mary Flomo",
    university: "SHARDA University, India",
    program: "MBBS Medicine",
    year: "2022",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80",
    story: "Getting into medical school abroad seemed impossible, but Tolbert Innovation Hub made it happen. Their counselors understood my academic background and matched me with the perfect university.",
    rating: 5,
  },
  {
    name: "Titus Mulbah",
    university: "Marwadi University, India",
    program: "BTech Mechanical Engineering",
    year: "2023",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&q=80",
    story: "The application process was smooth and stress-free thanks to the team. They handled all the paperwork and kept me updated throughout. Now I'm thriving at Marwadi University with a scholarship!",
    rating: 5,
  },
  {
    name: "Sia Kamara",
    university: "Graphic Era University, India",
    program: "BSc Nursing",
    year: "2024",
    image: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&q=80",
    story: "Tolbert Innovation Hub's counselors were knowledgeable and supportive. They helped me choose the right nursing program and walked me through every step from application to arrival in India.",
    rating: 5,
  },
];

export const scholarships = [
  {
    title: "Merit Excellence Scholarship",
    amount: "Up to 75% Tuition Waiver",
    universities: "Available at 12 Partner Universities",
    criteria: "GPA 3.5+ / WAEC Grade B+",
    deadline: "Rolling Admission",
    icon: "🏆",
    color: "from-yellow-400 to-orange-500",
  },
  {
    title: "International Student Grant",
    amount: "Up to $2,000/year",
    universities: "All Partner Universities",
    criteria: "International Student Status",
    deadline: "Before Registration",
    icon: "🌍",
    color: "from-blue-400 to-indigo-600",
  },
  {
    title: "Sports Achievement Award",
    amount: "Up to 50% Tuition Waiver",
    universities: "Selected Universities",
    criteria: "National Level Sports Achievement",
    deadline: "With Application",
    icon: "⚽",
    color: "from-green-400 to-teal-600",
  },
  {
    title: "STEM Innovation Scholarship",
    amount: "Up to 60% Tuition Waiver",
    universities: "8 Partner Universities",
    criteria: "Engineering / Science Programs",
    deadline: "Semester Basis",
    icon: "🔬",
    color: "from-purple-400 to-pink-600",
  },
];

export const stats = [
  { label: "Partner Universities", value: 17, suffix: "+" },
  { label: "Students Guided", value: 1000, suffix: "+" },
  { label: "Admission Success Rate", value: 95, suffix: "%" },
  { label: "Countries Available", value: 2, suffix: "" },
];
